### ISSUE TITLE
Support remapping of domains

### ISSUE THREAD

**Issue by mrzv** [denis-sokolov/chrome-supergenpass#63]
Some sites use different domains at different entry points (for example, gogoair.com and gogoinflight.com accept the same password). It would be nice if there was a way to provide a map to the extension (similar to the domain whitelist), where one could remap one domain to another.

**Comment by denis-sokolov** [comment]
I have reconsidered the option and it seems to be against the design of the extension.
This customization will make it likely we forget how to log in into a particular website. The value of supergenpass over password managers is the ability to regenerate passwords on a fresh computer without access to an existing computer. The remapping harms that. Because of that, it will not be added to the extension. Nevertheless, thank you for your suggestion!
