### ISSUE TITLE
Please port to Firefox

### ISSUE THREAD

**Issue by andreicristianpetcu** [denis-sokolov/chrome-supergenpass#91]
Hi! Do you have any plans to support Firefox? Firefox extensions have the same format as Chrome extensions these days. https://vimeo.com/241435808 There are a few different APIs but they are mostly the same https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by denis-sokolov** [comment]
No, I’m sorry. The extension is obscure enough as it is.

**Comment by chx** [comment]
With the recent news https://9to5google.com/2019/05/29/chrome-ad-blocking-enterprise-manifest-v3/ more or less forcing power users off Chrom, is there a chance you'd reconsider? Would money help? How much?

**Comment by denis-sokolov** [comment]
It’s safe to say that if I decide to move to Firefox, I will need this exension ported to Firefox. But at the moment I feel there is a lot of uncertainty to what exact degree will ad blocking be crippled and I am waiting to see how it turns out with time.

Unfortunately, money will not help. I am not open for a paid project, and if I move to Firefox, I will build it regardless of donations. Still, I appreciate it, thank you for the kind offer.
